<?xml version="1.0"?>
<!DOCTYPE hbci
[
<!ELEMENT hbci (DEGs,SEGs,SFs,MSGs)>

<!ELEMENT DEGs    (DEGdef)*>
<!ELEMENT SEGs    (SEGdef)*>
<!ELEMENT SFs     (SFdef)*>
<!ELEMENT MSGs    (MSGdef)*>

<!ELEMENT DEGdef ((DE | DEG)+,valids*,value*)>
<!ATTLIST DEGdef
  id ID #REQUIRED
  needsRequestTag (1) #IMPLIED
>

<!ELEMENT SEGdef ((DEG | DE)+,valids*,value*)>
<!ATTLIST SEGdef
  id ID #REQUIRED
  needsRequestTag (1) #IMPLIED
>

<!ELEMENT SFdef (SEG | SF)*>
<!ATTLIST SFdef
  id ID #REQUIRED
  needsRequestTag (1) #IMPLIED
>

<!ELEMENT MSGdef ((SEG | SF)+,valids*,value*)>
<!ATTLIST MSGdef
  id ID #REQUIRED
  dontsign (1) #IMPLIED
  dontcrypt (1) #IMPLIED
>

<!ELEMENT DE EMPTY>
<!ATTLIST DE
  name CDATA #REQUIRED
  type (AN | Bin | Code | Ctr | Cur | DTAUS | Date | Dig | ID | JN | Num | Time | Wrt) #REQUIRED
  minsize CDATA #IMPLIED
  maxsize CDATA #IMPLIED
  minnum CDATA "1"
  maxnum CDATA "1"
>

<!ELEMENT DEG EMPTY>
<!ATTLIST DEG
  type IDREF #REQUIRED
  name CDATA #IMPLIED
  minnum CDATA "1"
  maxnum CDATA "1"
>

<!ELEMENT SEG EMPTY>
<!ATTLIST SEG
  type IDREF #REQUIRED
  name CDATA #IMPLIED
  minnum CDATA "1"
  maxnum CDATA "1"
>

<!ELEMENT SF EMPTY>
<!ATTLIST SF
  type IDREF #REQUIRED
  name CDATA #IMPLIED
  minnum CDATA "1"
  maxnum CDATA "1"
>

<!ELEMENT valids (validvalue)+>
<!ATTLIST valids
  path CDATA #REQUIRED
>

<!ELEMENT validvalue (#PCDATA)>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
  path CDATA #REQUIRED
>

<!ENTITY MsgSigHeadInst
  '<SEG type="MsgHeadInst" name="MsgHead"/>
   <SEG type="SigHeadInst" name="SigHead" minnum="0"/>'
>

<!ENTITY MsgSigTailInst
  '<SEG type="SigTailInst" name="SigTail" minnum="0"/>
   <SEG type="MsgTailInst" name="MsgTail"/>'
>

<!ENTITY MsgSigHeadUser
  '<SEG type="MsgHeadUser" name="MsgHead"/>
   <SEG type="SigHeadUser" name="SigHead" minnum="0" maxnum="3"/>'
>

<!ENTITY MsgSigTailUser
  '<SEG type="SigTailUser" name="SigTail" minnum="0" maxnum="3"/>
   <SEG type="MsgTailUser" name="MsgTail"/>'
>

<!-- end of administrative entities -->

<!ENTITY GVP
  '<!-- 2.01 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DE name="maxnum" type="Num" maxsize="3"/>
   <DE name="minsigs" type="Num" maxsize="1"/>'
>
<!ENTITY GVP2
  '<!-- 3.0 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DE name="maxnum" type="Num" maxsize="3"/>
   <DE name="minsigs" type="Num" maxsize="1"/>
   <DE name="secclass" type="Code" maxsize="1"/>'
>
<!ENTITY SecClassValids
  '<valids path="secclass">
       <validvalue>0</validvalue>
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
       <validvalue>3</validvalue>
       <validvalue>4</validvalue>
   </valids>'
>
<!ENTITY SingleInlandInst1
  '<!-- 2.01 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTO" name="My"/>
   <DEG type="KTO" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage1" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="id" type="AN" maxsize="99" minnum="0"/>'
>
<!ENTITY SingleInlandUser1
  '<!-- 2.01 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTO" name="My"/>
   <DEG type="KTO" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage1" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="id" type="AN" maxsize="99" minnum="0"/>'
>

<!ENTITY SingleInlandInst2
  '<!-- 2.1 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTO" name="My"/>
   <DEG type="KTO" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage2" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="id" type="AN" maxsize="99" minnum="0"/>'
>
<!ENTITY SingleInlandUser2
  '<!-- 2.1 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTO" name="My"/>
   <DEG type="KTO" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage2" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="id" type="AN" maxsize="99" minnum="0"/>'
>

<!ENTITY SingleInlandInst3
  '<!-- 2.2 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTV2" name="My"/>
   <DEG type="KTV2" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage3" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="id" type="AN" maxsize="99" minnum="0"/>'
>
<!ENTITY SingleInlandUser3
  '<!-- 2.2 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTV2" name="My"/>
   <DEG type="KTV2" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage3" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="id" type="AN" maxsize="99" minnum="0"/>'
>

<!ENTITY SingleInlandInst4
  '<!-- 3.0 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTV3" name="My"/>
   <DEG type="KTV3" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage3" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="id" type="AN" maxsize="99" minnum="0"/>
   <DE name="status" type="Code" maxsize="1" minnum="0"/>'
>
<!ENTITY SingleInlandUser4
  '<!-- 3.0 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTV3" name="My"/>
   <DEG type="KTV3" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage3" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="id" type="AN" maxsize="99" minnum="0"/>'
>

<!ENTITY DauerInst1
  '<!-- 2.01 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTO" name="My"/>
   <DEG type="KTO" name="Other"/>
   <DE name="name" type="AN" maxsize="27"/>
   <DE name="name2" type="AN" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage1" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="orderid" type="AN" maxsize="99" minnum="0"/>
   <DEG type="DauerDetails"/>
   <DEG type="Aussetzung1" name="Aussetzung" minnum="0"/>'
>
<!ENTITY DauerUser1
  '<!-- 2.01 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTO" name="My"/>
   <DEG type="KTO" name="Other"/>
   <DE name="name" type="AN" maxsize="27"/>
   <DE name="name2" type="AN" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage1" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="orderid" type="AN" maxsize="99" minnum="0"/>
   <DEG type="DauerDetails"/>
   <DEG type="Aussetzung1" name="Aussetzung" minnum="0"/>'
>

<!ENTITY DauerInst2
  '<!-- 2.1 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTO" name="My"/>
   <DEG type="KTO" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage2" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="orderid" type="AN" maxsize="99" minnum="0"/>
   <DEG type="DauerDetails"/>
   <DEG type="Aussetzung2" name="Aussetzung" minnum="0"/>'
>
<!ENTITY DauerUser2
  '<!-- 2.1 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTO" name="My"/>
   <DEG type="KTO" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage2" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="orderid" type="AN" maxsize="99" minnum="0"/>
   <DEG type="DauerDetails"/>
   <DEG type="Aussetzung2" name="Aussetzung" minnum="0"/>'
>

<!ENTITY DauerInst3
  '<!-- 2.2 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTV2" name="My"/>
   <DEG type="KTV2" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage3" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="orderid" type="AN" maxsize="99" minnum="0"/>
   <DEG type="DauerDetails"/>
   <DEG type="Aussetzung2" name="Aussetzung" minnum="0"/>'
>
<!ENTITY DauerUser3
  '<!-- 2.2 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTV2" name="My"/>
   <DEG type="KTV2" name="Other"/>
   <DE name="name" type="DTAUS" maxsize="27"/>
   <DE name="name2" type="DTAUS" maxsize="27" minnum="0"/>
   <DEG type="BTG"/>
   <DE name="key" type="Dig" minsize="2" maxsize="2"/>
   <DE name="addkey" type="Dig" minsize="3" maxsize="3" minnum="0"/>
   <DEG type="usage3" name="usage" minnum="0"/>
   <DE name="date" type="Date" minnum="0"/>
   <DE name="orderid" type="AN" maxsize="99" minnum="0"/>
   <DEG type="DauerDetails"/>
   <DEG type="Aussetzung2" name="Aussetzung" minnum="0"/>'
>

<!ENTITY FestgeldInst1
  '<!-- 2.01 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTO" name="Anlagekto" minnum="0"/>
   <DE name="kontakt" type="ID" minnum="0"/>
   <DEG type="BTG" name="Anlagebetrag"/>
   <DEG type="FestCond1" name="FestCond"/>
   <DEG type="KTO" name="Belastungskto"/>
   <DE name="eigenerechnung" type="JN"/>
   <DE name="wiederanlage" type="Num" maxsize="1"/>
   <DE name="kontoauszug" type="Num" maxsize="1" minnum="0"/>
   <DEG type="KTO" name="Ausbuchungskto" minnum="0"/>
   <DEG type="KTO" name="Zinskto" minnum="0"/>
   <DEG type="FestCondVersion" minnum="0"/>
   <DEG type="BTG" name="Zinsbetrag" minnum="0"/>
   <DE name="status" type="Num" maxsize="1" minnum="0"/>
   <DEG type="Prolong" minnum="0"/> 
   
   <valids path="wiederanlage">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>
   <valids path="kontoauszug">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>'
>
<!ENTITY FestgeldUser1
  '<!-- 2.01 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTO" name="Anlagekto" minnum="0"/>
   <DE name="kontakt" type="ID" minnum="0"/>
   <DEG type="BTG" name="Anlagebetrag"/>
   <DEG type="FestCond1" name="FestCond"/>
   <DEG type="KTO" name="Belastungskto"/>
   <DE name="eigenerechnung" type="JN"/>
   <DE name="wiederanlage" type="Num" maxsize="1"/>
   <DE name="kontoauszug" type="Num" maxsize="1" minnum="0"/>
   <DEG type="KTO" name="Ausbuchungskto" minnum="0"/>
   <DEG type="KTO" name="Zinskto" minnum="0"/>
   <DEG type="FestCondVersion" minnum="0"/>
   <DEG type="BTG" name="Zinsbetrag" minnum="0"/>
   <DE name="status" type="Num" maxsize="1" minnum="0"/>
   <DEG type="Prolong" minnum="0"/> 
   
   <valids path="wiederanlage">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>
   <valids path="kontoauszug">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>'
>

<!ENTITY FestgeldInst2
  '<!-- 2.2 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTV2" name="Anlagekto" minnum="0"/>
   <DE name="kontakt" type="ID" minnum="0"/>
   <DEG type="BTG" name="Anlagebetrag"/>
   <DEG type="FestCond1" name="FestCond"/>
   <DEG type="KTV2" name="Belastungskto"/>
   <DE name="eigenerechnung" type="JN"/>
   <DE name="wiederanlage" type="Num" maxsize="1"/>
   <DE name="kontoauszug" type="Num" maxsize="1" minnum="0"/>
   <DEG type="KTV2" name="Ausbuchungskto" minnum="0"/>
   <DEG type="KTV2" name="Zinskto" minnum="0"/>
   <DEG type="FestCondVersion" minnum="0"/>
   <DEG type="BTG" name="Zinsbetrag" minnum="0"/>
   <DE name="status" type="Num" maxsize="1" minnum="0"/>
   <DEG type="Prolong" minnum="0"/> 
   
   <valids path="wiederanlage">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>
   <valids path="kontoauszug">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>'
>
<!ENTITY FestgeldUser2
  '<!-- 2.2 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTV2" name="Anlagekto" minnum="0"/>
   <DE name="kontakt" type="ID" minnum="0"/>
   <DEG type="BTG" name="Anlagebetrag"/>
   <DEG type="FestCond1" name="FestCond"/>
   <DEG type="KTV2" name="Belastungskto"/>
   <DE name="eigenerechnung" type="JN"/>
   <DE name="wiederanlage" type="Num" maxsize="1"/>
   <DE name="kontoauszug" type="Num" maxsize="1" minnum="0"/>
   <DEG type="KTV2" name="Ausbuchungskto" minnum="0"/>
   <DEG type="KTV2" name="Zinskto" minnum="0"/>
   <DEG type="FestCondVersion" minnum="0"/>
   <DEG type="BTG" name="Zinsbetrag" minnum="0"/>
   <DE name="status" type="Num" maxsize="1" minnum="0"/>
   <DEG type="Prolong" minnum="0"/> 
   
   <valids path="wiederanlage">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>
   <valids path="kontoauszug">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>'
>

<!ENTITY FestgeldInst3
  '<!-- 3.0 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTV3" name="Anlagekto" minnum="0"/>
   <DE name="kontakt" type="ID" minnum="0"/>
   <DEG type="BTG" name="Anlagebetrag"/>
   <DEG type="FestCond2" name="FestCond"/>
   <DEG type="KTV3" name="Belastungskto"/>
   <DE name="eigenerechnung" type="JN"/>
   <DE name="wiederanlage" type="Code" maxsize="1"/>
   <DE name="kontoauszug" type="Code" maxsize="1" minnum="0"/>
   <DEG type="KTV3" name="Ausbuchungskto" minnum="0"/>
   <DEG type="KTV3" name="Zinskto" minnum="0"/>
   <DEG type="FestCondVersion" minnum="0"/>
   <DEG type="BTG" name="Zinsbetrag" minnum="0"/>
   <DE name="status" type="Code" maxsize="1" minnum="0"/>
   <DEG type="Prolong" minnum="0"/> 
   
   <valids path="wiederanlage">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>
   <valids path="kontoauszug">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>
   <valids path="status">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>'
>
<!ENTITY FestgeldUser3
  '<!-- 3.0 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTV3" name="Anlagekto" minnum="0"/>
   <DE name="kontakt" type="ID" minnum="0"/>
   <DEG type="BTG" name="Anlagebetrag"/>
   <DEG type="FestCond2" name="FestCond"/>
   <DEG type="KTV3" name="Belastungskto"/>
   <DE name="eigenerechnung" type="JN"/>
   <DE name="wiederanlage" type="Code" maxsize="1"/>
   <DE name="kontoauszug" type="Code" maxsize="1" minnum="0"/>
   <DEG type="KTV3" name="Ausbuchungskto" minnum="0"/>
   <DEG type="KTV3" name="Zinskto" minnum="0"/>
   <DEG type="FestCondVersion" minnum="0"/>
   <DEG type="BTG" name="Zinsbetrag" minnum="0"/>
   <DE name="status" type="Code" maxsize="1" minnum="0"/>
   <DEG type="Prolong" minnum="0"/> 
   
   <valids path="wiederanlage">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>
   <valids path="kontoauszug">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>
   <valids path="status">
       <validvalue>1</validvalue>
       <validvalue>2</validvalue>
   </valids>'
>

<!ENTITY SammelInst1
  '<!-- 2.01 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DE name="data" type="Bin" maxsize="0"/>'
>
<!ENTITY SammelUser1
  '<!-- 2.01 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DE name="data" type="Bin" maxsize="0"/>'
>

<!ENTITY SammelInst2
  '<!-- 2.2 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTV2" name="KTV"/>
   <DE name="data" type="Bin" maxsize="0"/>'
>
<!ENTITY SammelUser2
  '<!-- 2.2 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTV2" name="KTV"/>
   <DE name="data" type="Bin" maxsize="0"/>'
>

<!ENTITY SammelInst3
  '<!-- 3.0 -->
   <DEG type="SegHeadInst" name="SegHead"/>
   <DEG type="KTV3" name="KTV"/>
   <DE name="data" type="Bin" maxsize="0"/>'
>
<!ENTITY SammelUser3
  '<!-- 3.0 -->
   <DEG type="SegHeadUser" name="SegHead"/>
   <DEG type="KTV3" name="KTV"/>
   <DE name="data" type="Bin" maxsize="0"/>'
>

<!ENTITY TANMedia1
    '<!-- 3.0 -->
    <DEG type="SegHeadUser" name="SegHead"/>
    <DE name="mediatype" type="Code" maxsize="1"/>
            
    <valids path="mediatype">
        <validvalue>0</validvalue>
        <validvalue>2</validvalue>
        <validvalue>3</validvalue>
    </valids>'           
>

<!ENTITY TANMedia2
    '<!-- 3.0 -->
    <DEG type="SegHeadUser" name="SegHead"/>
    <DE name="mediatype" type="Code" maxsize="1"/>
    <DE name="mediacategory" type="Code" maxsize="1"/>
            
    <valids path="mediatype">
        <validvalue>0</validvalue>
        <validvalue>2</validvalue>
        <validvalue>3</validvalue>
    </valids>           
    <valids path="mediacategory">
        <validvalue>A</validvalue>
        <validvalue>L</validvalue>
        <validvalue>G</validvalue>
        <validvalue>M</validvalue>
        <validvalue>S</validvalue>
    </valids>'           
>
]>

<hbci>
    <DEGs>
        <DEGdef id="AllowedGV">
            <DE name="code" type="AN" maxsize="6"/>
            <DE name="reqSigs" type="Num" maxsize="2"/>
            <DE name="limittype" type="Code" maxsize="1" minnum="0"/>
            <!-- DEG type="BTG" minnum="0"/-->
            <DE name="value" type="Wrt" minnum="0"/>
            <DE name="curr" type="Cur" minnum="0"/>            
            <DE name="limitdays" type="Num" maxsize="3" minnum="0"/>

            <valids path="reqSigs">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
                <validvalue>3</validvalue>

                <!-- Siehe http://www.onlinebanking-forum.de/phpBB2/viewtopic.php?t=14583 -->
                <validvalue>98</validvalue>
                <validvalue>99</validvalue>
            </valids>
            <valids path="limittype">
                <validvalue>E</validvalue>
                <validvalue>T</validvalue>
                <validvalue>W</validvalue>
                <validvalue>M</validvalue>
                <validvalue>Z</validvalue>
            </valids>
        </DEGdef>

        <DEGdef id="BTG">
            <DE name="value" type="Wrt"/>
            <DE name="curr" type="Cur"/>
        </DEGdef>

        <DEGdef id="Cert">
            <DE name="type" type="Code" maxsize="1"/>
            <DE name="cert" type="Bin" maxsize="2048"/>

            <valids path="type">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
                <validvalue>3</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="CryptAlg">
            <DE name="use" type="Code" maxsize="3"/>
            <DE name="mode" type="Code" maxsize="3"/>
            <DE name="alg" type="Code" maxsize="3"/>
            <DE name="enckey" type="Bin" maxsize="512"/>
            <DE name="keytype" type="Code" maxsize="3"/>
            <DE name="ivname" type="Code" maxsize="3"/>
            <DE name="iv" type="Bin" maxsize="512" minnum="0"/>

            <valids path="mode">
                <validvalue>2</validvalue>
                <validvalue>16</validvalue>
                <validvalue>17</validvalue>
                <validvalue>18</validvalue>
                <validvalue>19</validvalue>
            </valids>
            <valids path="alg">
                <validvalue>13</validvalue>
                <validvalue>14</validvalue> <!-- AES-256 -->
            </valids>
            <valids path="keytype">
                <validvalue>5</validvalue>
                <validvalue>6</validvalue>
            </valids>

            <value path="use">2</value>
            <value path="ivname">1</value>
        </DEGdef>

        <DEGdef id="HashAlg">
            <DE name="usage" type="Code" maxsize="3"/>
            <DE name="alg" type="Code" maxsize="3"/>
            <DE name="parname" type="Code" maxsize="3"/>
            <DE name="parameter" type="Bin" maxsize="512" minnum="0"/>
            
            <valids path="alg">
                <validvalue>1</validvalue>
                <validvalue>3</validvalue>
                <validvalue>4</validvalue>
                <validvalue>5</validvalue>
                <validvalue>6</validvalue>
                <validvalue>999</validvalue>
            </valids>

            <value path="usage">1</value>
            <value path="parname">1</value>
        </DEGdef>
        
        <DEGdef id="KeyName">
            <DEG type="KIK"/>
            <DE name="userid" type="ID"/>
            <DE name="keytype" type="AN" maxsize="1"/>
            <DE name="keynum" type="Num" maxsize="3"/>
            <DE name="keyversion" type="Num" maxsize="3"/>

            <valids path="keytype">
                <validvalue>D</validvalue>
                <validvalue>S</validvalue>
                <validvalue>V</validvalue>
            </valids>
        </DEGdef>

        <DEGdef id="KIK">
            <DE name="country" type="Ctr"/>
            <DE name="blz" type="AN" maxsize="30" minnum="0"/>
        </DEGdef>

        <DEGdef id="KLimit">
            <DE name="limittype" type="Code" maxsize="1"/>
            <DEG type="BTG" minnum="0"/>
            <DE name="limitdays" type="Num" maxsize="3" minnum="0"/>

            <valids path="limittype">
                <validvalue>E</validvalue>
                <validvalue>T</validvalue>
                <validvalue>W</validvalue>
                <validvalue>M</validvalue>
                <validvalue>Z</validvalue>
            </valids>
        </DEGdef>

        <DEGdef id="MsgRef">
            <DE name="dialogid" type="ID"/>
            <DE name="msgnum" type="Num" maxsize="4"/>
        </DEGdef>
        
        <DEGdef id="PubKey">
            <DE name="usage" type="Code" maxsize="3"/>
            <DE name="mode" type="Code" maxsize="3"/>
            <DE name="method" type="Code" maxsize="3"/>
            <DE name="modulus" type="Bin" maxsize="512"/>
            <DE name="modname" type="Code" maxsize="3"/>
            <DE name="exponent" type="Bin" maxsize="512"/>
            <DE name="expname" type="Code" maxsize="3"/>

            <valids path="usage">
                <validvalue>5</validvalue>
                <validvalue>6</validvalue>
            </valids>
            <valids path="mode">
                <validvalue>2</validvalue>
                <validvalue>16</validvalue>
                <validvalue>17</validvalue>
                <validvalue>18</validvalue>
                <validvalue>19</validvalue>
                <validvalue>999</validvalue>
            </valids>

            <value path="method">10</value>
            <value path="modname">12</value>
            <value path="expname">13</value>
        </DEGdef>

        <DEGdef id="RetVal">
            <DE name="code" type="Dig" minsize="4" maxsize="4"/>
            <DE name="ref" type="AN" maxsize="7" minnum="0"/>
            <DE name="text" type="AN" maxsize="80"/>
            <DE name="parm" type="AN" maxsize="35" minnum="0" maxnum="10"/>
        </DEGdef>

        <DEGdef id="SecIdnDetails">
            <DE name="func" type="Code" maxsize="3"/>
            <DE name="cid" type="Bin" maxsize="256" minnum="0"/>
            <DE name="sysid" type="ID" minnum="0"/>

            <valids path="func">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="SecProfile">
            <DE name="method" type="Code" minsize="3" maxsize="3"/>
            <DE name="version" type="Num" maxsize="3" maxnum="9"/>
            
            <valids path="method">
                <validvalue>DDV</validvalue>
                <validvalue>RDH</validvalue>
                <validvalue>RAH</validvalue>
                <validvalue>PIN</validvalue>
            </valids>
            <valids path="version">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
                <validvalue>3</validvalue>
                <validvalue>4</validvalue>
                <validvalue>5</validvalue>
                <validvalue>6</validvalue>
                <validvalue>7</validvalue>
                <validvalue>8</validvalue>
                <validvalue>9</validvalue>
                <validvalue>10</validvalue>
            </valids>
        </DEGdef>

        <DEGdef id="SecTimestamp">
            <DE name="type" type="AN" maxsize="3"/>
            <DE name="date" type="Date" minnum="0"/>
            <DE name="time" type="Time" minnum="0"/>

            <valids path="type">
                <validvalue>1</validvalue>
                <validvalue>6</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="SegHeadInst">
            <DE name="code" type="AN" maxsize="6"/>
            <DE name="seq" type="Num" maxsize="3"/>
            <DE name="version" type="Num" maxsize="3"/>
            <DE name="ref" type="Num" maxsize="3" minnum="0"/>
        </DEGdef>
        <DEGdef id="SegHeadUser">
            <DE name="code" type="AN" maxsize="6"/>
            <DE name="seq" type="Num" maxsize="3"/>
            <DE name="version" type="Num" maxsize="3"/>
            <DE name="ref" type="Num" maxsize="3" minnum="0"/>
        </DEGdef>

        <DEGdef id="SigAlg">
            <DE name="usage" type="Code" maxsize="3"/>
            <DE name="alg" type="Code" maxsize="3"/>
            <DE name="mode" type="AN" maxsize="999"/>

            <valids path="alg">
                <validvalue>1</validvalue>
                <validvalue>10</validvalue>
            </valids>
            <valids path="mode">
                <validvalue>999</validvalue>
                <validvalue>16</validvalue>
                <validvalue>17</validvalue>
                <validvalue>18</validvalue>
                <validvalue>19</validvalue>
            </valids>

            <value path="usage">6</value>
        </DEGdef>

        <DEGdef id="SuppCompMethods">
            <DE name="func" type="Code" maxsize="3"/>
            <DE name="version" type="Num" maxsize="3" maxnum="9"/>

            <valids path="func">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
                <validvalue>3</validvalue>
                <validvalue>4</validvalue>
                <validvalue>5</validvalue>
                <validvalue>6</validvalue>
                <validvalue>7</validvalue>
                <validvalue>999</validvalue>
            </valids>
        </DEGdef>

        <DEGdef id="SuppLangs">
            <DE name="lang" type="Num" maxsize="3" maxnum="9"/>

            <valids path="lang">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
                <validvalue>3</validvalue>
            </valids>
        </DEGdef>

        <DEGdef id="SuppSecMethods">
            <DE name="method" type="AN" minsize="3" maxsize="3"/>
            <DE name="version" type="Num" maxsize="3" maxnum="9"/>
        </DEGdef>

        <DEGdef id="SuppVersions">
            <DE name="version" type="Num" maxsize="3" maxnum="9"/>
            
            <valids path="version">
                <validvalue>201</validvalue>
                <validvalue>210</validvalue>
                <validvalue>220</validvalue>
                <validvalue>300</validvalue>
                <validvalue>400</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="UserSig">
            <DE name="pin" type="AN" maxsize="99"/>               <!-- Einige Banken unterstützen mehr als 6 Stellen  -->
            <DE name="tan" type="AN" maxsize="99" minnum="0"/>
        </DEGdef>

        <!-- end of administrative degs -->
    
        <DEGdef id="Address1"> <!-- 2.01 -->
            <DE name="name1" type="AN" maxsize="35"/>
            <DE name="name2" type="AN" maxsize="35" minnum="0"/>
            <DE name="street_pf" type="AN" maxsize="35"/>
            <DE name="plz_ort" type="AN" maxsize="35"/>
            <DE name="tel" type="AN" maxsize="35" minnum="0"/>